// apps/sandbox/react/src/samples/button-group/nested.tsx
import { Button, ButtonGroup } from '@aranghat/base-react';

export default function Nested() {
  return (
    <>
      <ButtonGroup>
        <ButtonGroup>
          <Button variant="outline">1</Button>
          <Button variant="outline">2</Button>
          <Button variant="outline">3</Button>
        </ButtonGroup>
        <ButtonGroup>
          <Button variant="outline">Next</Button>
        </ButtonGroup>
      </ButtonGroup>
    </>
  );
}

// apps/sandbox/angular/src/app/samples/button-group/nested.ts
import { Component } from '@angular/core';
import { ArtButton, ArtButtonGroup } from '@aranghat/base-angular';

@Component({
  selector: 'sample-button-group-nested',
  imports: [ArtButton, ArtButtonGroup],
  template: `
    <art-button-group>
      <art-button-group>
        <art-button variant="outline">1</art-button>
        <art-button variant="outline">2</art-button>
        <art-button variant="outline">3</art-button>
      </art-button-group>
      <art-button-group>
        <art-button variant="outline">Next</art-button>
      </art-button-group>
    </art-button-group>
  `,
})
export class ButtonGroupNested {}
