// apps/sandbox/react/src/samples/button-group/sizes.tsx
import { Button, ButtonGroup } from '@aranghat/base-react';

export default function Sizes() {
  return (
    <>
      <ButtonGroup>
        <Button variant="outline" size="sm">Small</Button>
        <Button variant="outline" size="sm">Small</Button>
      </ButtonGroup>
      <ButtonGroup>
        <Button variant="outline" size="lg">Large</Button>
        <Button variant="outline" size="lg">Large</Button>
      </ButtonGroup>
    </>
  );
}

// apps/sandbox/angular/src/app/samples/button-group/sizes.ts
import { Component } from '@angular/core';
import { ArtButton, ArtButtonGroup } from '@aranghat/base-angular';

@Component({
  selector: 'sample-button-group-sizes',
  imports: [ArtButton, ArtButtonGroup],
  template: `
    <art-button-group>
      <art-button variant="outline" size="sm">Small</art-button>
      <art-button variant="outline" size="sm">Small</art-button>
    </art-button-group>
    <art-button-group>
      <art-button variant="outline" size="lg">Large</art-button>
      <art-button variant="outline" size="lg">Large</art-button>
    </art-button-group>
  `,
})
export class ButtonGroupSizes {}
