// apps/sandbox/angular/src/app/samples/message/attachments.ts
import { Component } from '@angular/core';
import { ArtAttachment, ArtAvatar, ArtBubble, ArtMessage } from '@aranghat/components-angular';

@Component({
  selector: 'sample-message-attachments',
  imports: [ArtAttachment, ArtAvatar, ArtBubble, ArtMessage],
  template: `
    <art-message align="end">
      <art-avatar slot="avatar" size="sm" alt="">ME</art-avatar>
      <art-bubble>Here are the files.</art-bubble>
      <art-attachment name="q3-results.pdf" description="PDF · 1.2 MB"></art-attachment>
    </art-message>
  `,
})
export class MessageAttachments {}

// apps/sandbox/react/src/samples/message/attachments.tsx
import { Attachment, Avatar, Bubble, Message } from '@aranghat/components-react';

export default function Attachments() {
  return (
    <>
      <Message align="end">
        <Avatar slot="avatar" size="sm" alt="">ME</Avatar>
        <Bubble>Here are the files.</Bubble>
        <Attachment name="q3-results.pdf" description="PDF · 1.2 MB" />
      </Message>
    </>
  );
}
