// apps/sandbox/angular/src/app/samples/tooltip/delays.ts
import { Component } from '@angular/core';
import { ArtTooltip } from '@aranghat/components-angular';
import { ArtButton } from '@aranghat/base-angular';

@Component({
  selector: 'sample-tooltip-delays',
  imports: [ArtButton, ArtTooltip],
  template: `
    <art-tooltip open-delay="0" close-delay="0">
      <art-button slot="trigger" variant="outline">Instant</art-button>
      No hover intent
    </art-tooltip>
  `,
})
export class TooltipDelays {}

// apps/sandbox/react/src/samples/tooltip/delays.tsx
import { Tooltip } from '@aranghat/components-react';
import { Button } from '@aranghat/base-react';

export default function Delays() {
  return (
    <>
      <Tooltip openDelay="0" closeDelay="0">
        <Button slot="trigger" variant="outline">Instant</Button>
        No hover intent
      </Tooltip>
    </>
  );
}
