// apps/sandbox/vue/src/App.vue
<script setup lang="ts">
import type { Component } from 'vue';

const modules = import.meta.glob('./samples/**/*.vue', { eager: true }) as Record<string, { default: Component }>;
const samples = Object.entries(modules)
  .sort()
  .map(([path, mod]) => ({ id: path.replace('./samples/', '').replace(/\.vue$/, ''), component: mod.default }));
</script>

<template>
  <section v-for="s in samples" :key="s.id" :data-sample="s.id">
    <h2>{{ s.id }}</h2>
    <component :is="s.component" />
  </section>
</template>

// apps/sandbox/react/src/App.tsx
import type { ComponentType } from 'react';

const samples = import.meta.glob('./samples/**/*.tsx', { eager: true }) as Record<string, { default: ComponentType }>;

export function App() {
  return (
    <main>
      {Object.entries(samples)
        .sort()
        .map(([path, mod]) => {
          const id = path.replace('./samples/', '').replace(/\.tsx$/, '');
          const Sample = mod.default;
          return (
            <section key={id} data-sample={id}>
              <h2>{id}</h2>
              <Sample />
            </section>
          );
        })}
    </main>
  );
}
