// apps/sandbox/angular/src/app/samples/sheet/sides.ts
import { Component } from '@angular/core';
import { ArtSheet } from '@aranghat/modals-angular';
import { ArtButton, ArtField, ArtInput, ArtLabel } from '@aranghat/base-angular';

@Component({
  selector: 'sample-sheet-sides',
  imports: [ArtButton, ArtField, ArtInput, ArtLabel, ArtSheet],
  template: `
    <art-sheet side="top">
      <art-button slot="trigger" variant="outline">Top</art-button>
      <span slot="title">Edit profile</span>
      <span slot="description">Make changes to your profile here. Click save when you're done.</span>
      <art-field>
        <art-label slot="label">Name</art-label>
        <art-input value="Pedro Duarte"></art-input>
      </art-field>
      <art-field>
        <art-label slot="label">Username</art-label>
        <art-input value="@peduarte"></art-input>
      </art-field>
      <art-button slot="footer">Save changes</art-button>
      <art-button slot="footer" variant="outline" dialog-close>Close</art-button>
    </art-sheet>
    <art-sheet side="right">
      <art-button slot="trigger" variant="outline">Right</art-button>
      <span slot="title">Edit profile</span>
      <span slot="description">Make changes to your profile here. Click save when you're done.</span>
      <art-field>
        <art-label slot="label">Name</art-label>
        <art-input value="Pedro Duarte"></art-input>
      </art-field>
      <art-field>
        <art-label slot="label">Username</art-label>
        <art-input value="@peduarte"></art-input>
      </art-field>
      <art-button slot="footer">Save changes</art-button>
      <art-button slot="footer" variant="outline" dialog-close>Close</art-button>
    </art-sheet>
    <art-sheet side="bottom">
      <art-button slot="trigger" variant="outline">Bottom</art-button>
      <span slot="title">Edit profile</span>
      <span slot="description">Make changes to your profile here. Click save when you're done.</span>
      <art-field>
        <art-label slot="label">Name</art-label>
        <art-input value="Pedro Duarte"></art-input>
      </art-field>
      <art-field>
        <art-label slot="label">Username</art-label>
        <art-input value="@peduarte"></art-input>
      </art-field>
      <art-button slot="footer">Save changes</art-button>
      <art-button slot="footer" variant="outline" dialog-close>Close</art-button>
    </art-sheet>
    <art-sheet side="left">
      <art-button slot="trigger" variant="outline">Left</art-button>
      <span slot="title">Edit profile</span>
      <span slot="description">Make changes to your profile here. Click save when you're done.</span>
      <art-field>
        <art-label slot="label">Name</art-label>
        <art-input value="Pedro Duarte"></art-input>
      </art-field>
      <art-field>
        <art-label slot="label">Username</art-label>
        <art-input value="@peduarte"></art-input>
      </art-field>
      <art-button slot="footer">Save changes</art-button>
      <art-button slot="footer" variant="outline" dialog-close>Close</art-button>
    </art-sheet>
  `,
})
export class SheetSides {}

// apps/sandbox/react/src/samples/sheet/sides.tsx
import { Sheet } from '@aranghat/modals-react';
import { Button, Field, Input, Label } from '@aranghat/base-react';

export default function Sides() {
  return (
    <>
      <Sheet side="top">
        <Button slot="trigger" variant="outline">Top</Button>
        <span slot="title">Edit profile</span>
        <span slot="description">Make changes to your profile here. Click save when you're done.</span>
        <Field>
          <Label slot="label">Name</Label>
          <Input value="Pedro Duarte" />
        </Field>
        <Field>
          <Label slot="label">Username</Label>
          <Input value="@peduarte" />
        </Field>
        <Button slot="footer">Save changes</Button>
        <Button slot="footer" variant="outline" dialog-close>Close</Button>
      </Sheet>
      <Sheet side="right">
        <Button slot="trigger" variant="outline">Right</Button>
        <span slot="title">Edit profile</span>
        <span slot="description">Make changes to your profile here. Click save when you're done.</span>
        <Field>
          <Label slot="label">Name</Label>
          <Input value="Pedro Duarte" />
        </Field>
        <Field>
          <Label slot="label">Username</Label>
          <Input value="@peduarte" />
        </Field>
        <Button slot="footer">Save changes</Button>
        <Button slot="footer" variant="outline" dialog-close>Close</Button>
      </Sheet>
      <Sheet side="bottom">
        <Button slot="trigger" variant="outline">Bottom</Button>
        <span slot="title">Edit profile</span>
        <span slot="description">Make changes to your profile here. Click save when you're done.</span>
        <Field>
          <Label slot="label">Name</Label>
          <Input value="Pedro Duarte" />
        </Field>
        <Field>
          <Label slot="label">Username</Label>
          <Input value="@peduarte" />
        </Field>
        <Button slot="footer">Save changes</Button>
        <Button slot="footer" variant="outline" dialog-close>Close</Button>
      </Sheet>
      <Sheet side="left">
        <Button slot="trigger" variant="outline">Left</Button>
        <span slot="title">Edit profile</span>
        <span slot="description">Make changes to your profile here. Click save when you're done.</span>
        <Field>
          <Label slot="label">Name</Label>
          <Input value="Pedro Duarte" />
        </Field>
        <Field>
          <Label slot="label">Username</Label>
          <Input value="@peduarte" />
        </Field>
        <Button slot="footer">Save changes</Button>
        <Button slot="footer" variant="outline" dialog-close>Close</Button>
      </Sheet>
    </>
  );
}
