// apps/sandbox/angular/src/app/samples/drawer/persistent.ts
import { Component } from '@angular/core';
import { ArtDrawer } from '@aranghat/modals-angular';
import { ArtButton } from '@aranghat/base-angular';

@Component({
  selector: 'sample-drawer-persistent',
  imports: [ArtButton, ArtDrawer],
  template: `
    <art-drawer persistent>
      <art-button slot="trigger" variant="outline">Pick a plan</art-button>
      <span slot="title">Choose a plan</span>
      <span slot="description">You need to pick one to continue.</span>
      <art-button slot="footer" dialog-close>Free</art-button>
      <art-button slot="footer" variant="outline" dialog-close>Pro</art-button>
    </art-drawer>
  `,
})
export class DrawerPersistent {}

// apps/sandbox/react/src/samples/drawer/persistent.tsx
import { Drawer } from '@aranghat/modals-react';
import { Button } from '@aranghat/base-react';

export default function Persistent() {
  return (
    <>
      <Drawer persistent>
        <Button slot="trigger" variant="outline">Pick a plan</Button>
        <span slot="title">Choose a plan</span>
        <span slot="description">You need to pick one to continue.</span>
        <Button slot="footer" dialog-close>Free</Button>
        <Button slot="footer" variant="outline" dialog-close>Pro</Button>
      </Drawer>
    </>
  );
}
