// apps/sandbox/react/src/samples/bubble/links.tsx
import { Bubble } from '@aranghat/components-react';

export default function Links() {
  return (
    <>
      <Bubble variant="outline" href="https://example.com" target="_blank" rel="noreferrer">Open the shared document ↗</Bubble>
      <Bubble variant="muted">Reply with <a href="#">a link</a> inside the text.</Bubble>
    </>
  );
}

// apps/sandbox/angular/src/app/samples/bubble/links.ts
import { Component } from '@angular/core';
import { ArtBubble } from '@aranghat/components-angular';

@Component({
  selector: 'sample-bubble-links',
  imports: [ArtBubble],
  template: `
    <art-bubble variant="outline" href="https://example.com" target="_blank" rel="noreferrer">Open the shared document ↗</art-bubble>
    <art-bubble variant="muted">Reply with <a href="#">a link</a> inside the text.</art-bubble>
  `,
})
export class BubbleLinks {}
