// apps/sandbox/react/src/samples/bubble/variants.tsx
import { Bubble } from '@aranghat/components-react';

export default function Variants() {
  return (
    <>
      <Bubble variant="default">Default bubble</Bubble>
      <Bubble variant="secondary">Secondary bubble</Bubble>
      <Bubble variant="muted">Muted bubble</Bubble>
      <Bubble variant="tinted">Tinted bubble</Bubble>
      <Bubble variant="outline">Outline bubble</Bubble>
      <Bubble variant="ghost">Ghost bubble</Bubble>
      <Bubble variant="destructive">Destructive bubble</Bubble>
    </>
  );
}

// apps/sandbox/angular/src/app/samples/bubble/variants.ts
import { Component } from '@angular/core';
import { ArtBubble } from '@aranghat/components-angular';

@Component({
  selector: 'sample-bubble-variants',
  imports: [ArtBubble],
  template: `
    <art-bubble variant="default">Default bubble</art-bubble>
    <art-bubble variant="secondary">Secondary bubble</art-bubble>
    <art-bubble variant="muted">Muted bubble</art-bubble>
    <art-bubble variant="tinted">Tinted bubble</art-bubble>
    <art-bubble variant="outline">Outline bubble</art-bubble>
    <art-bubble variant="ghost">Ghost bubble</art-bubble>
    <art-bubble variant="destructive">Destructive bubble</art-bubble>
  `,
})
export class BubbleVariants {}
