// apps/sandbox/react/src/samples/dropdown-menu/submenu.tsx
import { DropdownMenu, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuSub } from '@aranghat/navigation-react';
import { Button } from '@aranghat/base-react';

export default function Submenu() {
  return (
    <>
      <DropdownMenu open>
        <Button slot="trigger" variant="outline">Open</Button>
        <DropdownMenuItem value="new">New file</DropdownMenuItem>
        <DropdownMenuSub open>
          <DropdownMenuItem slot="trigger">Share</DropdownMenuItem>
          <DropdownMenuItem value="email">Email</DropdownMenuItem>
          <DropdownMenuItem value="message">Message</DropdownMenuItem>
          <DropdownMenuSeparator />
          <DropdownMenuItem value="more">More…</DropdownMenuItem>
        </DropdownMenuSub>
        <DropdownMenuSeparator />
        <DropdownMenuItem value="delete" variant="destructive">Delete</DropdownMenuItem>
      </DropdownMenu>
    </>
  );
}

// apps/sandbox/angular/src/app/samples/dropdown-menu/submenu.ts
import { Component } from '@angular/core';
import { ArtDropdownMenu, ArtDropdownMenuItem, ArtDropdownMenuSeparator, ArtDropdownMenuSub } from '@aranghat/navigation-angular';
import { ArtButton } from '@aranghat/base-angular';

@Component({
  selector: 'sample-dropdown-menu-submenu',
  imports: [ArtButton, ArtDropdownMenu, ArtDropdownMenuItem, ArtDropdownMenuSeparator, ArtDropdownMenuSub],
  template: `
    <art-dropdown-menu open>
      <art-button slot="trigger" variant="outline">Open</art-button>
      <art-dropdown-menu-item value="new">New file</art-dropdown-menu-item>
      <art-dropdown-menu-sub open>
        <art-dropdown-menu-item slot="trigger">Share</art-dropdown-menu-item>
        <art-dropdown-menu-item value="email">Email</art-dropdown-menu-item>
        <art-dropdown-menu-item value="message">Message</art-dropdown-menu-item>
        <art-dropdown-menu-separator></art-dropdown-menu-separator>
        <art-dropdown-menu-item value="more">More…</art-dropdown-menu-item>
      </art-dropdown-menu-sub>
      <art-dropdown-menu-separator></art-dropdown-menu-separator>
      <art-dropdown-menu-item value="delete" variant="destructive">Delete</art-dropdown-menu-item>
    </art-dropdown-menu>
  `,
})
export class DropdownMenuSubmenu {}
