// apps/sandbox/react/src/samples/typography/list.tsx
import { Typography } from '@aranghat/base-react';

export default function List() {
  return (
    <>
      <Typography>
        <ol>
          <li>Install the package</li>
          <li>Import the token sheet</li>
          <li>Use the components</li>
        </ol>
        <hr />
        <ul>
          <li>HTML</li>
          <li>React, Vue and Angular</li>
        </ul>
      </Typography>
    </>
  );
}

// apps/sandbox/angular/src/app/samples/typography/list.ts
import { Component } from '@angular/core';
import { ArtTypography } from '@aranghat/base-angular';

@Component({
  selector: 'sample-typography-list',
  imports: [ArtTypography],
  template: `
    <art-typography>
      <ol>
        <li>Install the package</li>
        <li>Import the token sheet</li>
        <li>Use the components</li>
      </ol>
      <hr>
      <ul>
        <li>HTML</li>
        <li>React, Vue and Angular</li>
      </ul>
    </art-typography>
  `,
})
export class TypographyList {}
