// apps/sandbox/react/src/samples/combobox/open.tsx
import { Combobox, ComboboxItem } from '@aranghat/components-react';

export default function Open() {
  return (
    <>
      <Combobox value="nuxt" aria-label="Framework" open>
        <ComboboxItem value="next">Next.js</ComboboxItem>
        <ComboboxItem value="sveltekit">SvelteKit</ComboboxItem>
        <ComboboxItem value="nuxt">Nuxt.js</ComboboxItem>
        <ComboboxItem value="remix" disabled>Remix</ComboboxItem>
        <ComboboxItem value="astro">Astro</ComboboxItem>
      </Combobox>
    </>
  );
}

// apps/sandbox/angular/src/app/samples/combobox/open.ts
import { Component } from '@angular/core';
import { ArtCombobox, ArtComboboxItem } from '@aranghat/components-angular';

@Component({
  selector: 'sample-combobox-open',
  imports: [ArtCombobox, ArtComboboxItem],
  template: `
    <art-combobox value="nuxt" aria-label="Framework" open>
      <art-combobox-item value="next">Next.js</art-combobox-item>
      <art-combobox-item value="sveltekit">SvelteKit</art-combobox-item>
      <art-combobox-item value="nuxt">Nuxt.js</art-combobox-item>
      <art-combobox-item value="remix" disabled>Remix</art-combobox-item>
      <art-combobox-item value="astro">Astro</art-combobox-item>
    </art-combobox>
  `,
})
export class ComboboxOpen {}
