// apps/sandbox/react/src/samples/separator/vertical.tsx
import { Button, Separator } from '@aranghat/base-react';

export default function Vertical() {
  return (
    <>
      <Button variant="ghost">Blog</Button>
      <Separator orientation="vertical" />
      <Button variant="ghost">Docs</Button>
      <Separator orientation="vertical" />
      <Button variant="ghost">Source</Button>
    </>
  );
}

// apps/sandbox/angular/src/app/samples/separator/vertical.ts
import { Component } from '@angular/core';
import { ArtButton, ArtSeparator } from '@aranghat/base-angular';

@Component({
  selector: 'sample-separator-vertical',
  imports: [ArtButton, ArtSeparator],
  template: `
    <art-button variant="ghost">Blog</art-button>
    <art-separator orientation="vertical"></art-separator>
    <art-button variant="ghost">Docs</art-button>
    <art-separator orientation="vertical"></art-separator>
    <art-button variant="ghost">Source</art-button>
  `,
})
export class SeparatorVertical {}
