// apps/sandbox/angular/src/app/samples/radio-group/horizontal.ts
import { Component } from '@angular/core';
import { ArtRadio, ArtRadioGroup } from '@aranghat/base-angular';

@Component({
  selector: 'sample-radio-group-horizontal',
  imports: [ArtRadio, ArtRadioGroup],
  template: `
    <art-radio-group orientation="horizontal" value="default" aria-label="Density">
      <art-radio value="default">Default</art-radio>
      <art-radio value="comfortable">Comfortable</art-radio>
      <art-radio value="compact">Compact</art-radio>
    </art-radio-group>
  `,
})
export class RadioGroupHorizontal {}

// apps/sandbox/react/src/samples/radio-group/horizontal.tsx
import { Radio, RadioGroup } from '@aranghat/base-react';

export default function Horizontal() {
  return (
    <>
      <RadioGroup orientation="horizontal" value="default" aria-label="Density">
        <Radio value="default">Default</Radio>
        <Radio value="comfortable">Comfortable</Radio>
        <Radio value="compact">Compact</Radio>
      </RadioGroup>
    </>
  );
}
