// apps/sandbox/angular/src/app/samples/hover-card/open.ts
import { Component } from '@angular/core';
import { ArtHoverCard } from '@aranghat/components-angular';
import { ArtButton } from '@aranghat/base-angular';

@Component({
  selector: 'sample-hover-card-open',
  imports: [ArtButton, ArtHoverCard],
  template: `
    <art-hover-card open>
      <art-button slot="trigger" variant="link">@nextjs</art-button>
      <h4>@nextjs</h4>
      <p>The React Framework – created and maintained by @vercel.</p>
      <p class="muted">Joined December 2021</p>
    </art-hover-card>
  `,
})
export class HoverCardOpen {}

// apps/sandbox/react/src/samples/hover-card/open.tsx
import { HoverCard } from '@aranghat/components-react';
import { Button } from '@aranghat/base-react';

export default function Open() {
  return (
    <>
      <HoverCard open>
        <Button slot="trigger" variant="link">@nextjs</Button>
        <h4>@nextjs</h4>
        <p>The React Framework – created and maintained by @vercel.</p>
        <p className="muted">Joined December 2021</p>
      </HoverCard>
    </>
  );
}
