// apps/sandbox/angular/src/app/samples/button-group/vertical.ts
import { Component } from '@angular/core';
import { ArtButton, ArtButtonGroup } from '@aranghat/base-angular';

@Component({
  selector: 'sample-button-group-vertical',
  imports: [ArtButton, ArtButtonGroup],
  template: `
    <art-button-group orientation="vertical">
      <art-button variant="outline">Top</art-button>
      <art-button variant="outline">Middle</art-button>
      <art-button variant="outline">Bottom</art-button>
    </art-button-group>
  `,
})
export class ButtonGroupVertical {}

// apps/sandbox/react/src/samples/button-group/vertical.tsx
import { Button, ButtonGroup } from '@aranghat/base-react';

export default function Vertical() {
  return (
    <>
      <ButtonGroup orientation="vertical">
        <Button variant="outline">Top</Button>
        <Button variant="outline">Middle</Button>
        <Button variant="outline">Bottom</Button>
      </ButtonGroup>
    </>
  );
}
