// apps/sandbox/react/src/samples/carousel/vertical.tsx
import { Carousel, CarouselItem } from '@aranghat/components-react';
import { Card } from '@aranghat/base-react';

export default function Vertical() {
  return (
    <>
      <Carousel orientation="vertical" aria-label="Numbers" style={{ maxWidth: 'var(--art-container-xs)', marginBlock: 'var(--art-space-12)' }}>
        <CarouselItem>
          <Card><p className="slide">1</p></Card>
        </CarouselItem>
        <CarouselItem>
          <Card><p className="slide">2</p></Card>
        </CarouselItem>
        <CarouselItem>
          <Card><p className="slide">3</p></Card>
        </CarouselItem>
        <CarouselItem>
          <Card><p className="slide">4</p></Card>
        </CarouselItem>
        <CarouselItem>
          <Card><p className="slide">5</p></Card>
        </CarouselItem>
      </Carousel>
    </>
  );
}

// apps/sandbox/angular/src/app/samples/slider/vertical.ts
import { Component } from '@angular/core';
import { ArtSlider } from '@aranghat/base-angular';

@Component({
  selector: 'sample-slider-vertical',
  imports: [ArtSlider],
  template: `
    <art-slider orientation="vertical" value="60" aria-label="Level"></art-slider>
  `,
})
export class SliderVertical {}
