// apps/sandbox/react/src/samples/input-otp/with-label.tsx
import { Field, InputOtp, Label } from '@aranghat/base-react';

export default function WithLabel() {
  return (
    <>
      <Field>
        <Label slot="label">Verification code</Label>
        <InputOtp groupSize="3" />
        <p slot="description">Enter the 6-digit code we sent to your phone.</p>
      </Field>
    </>
  );
}

// apps/sandbox/angular/src/app/samples/input-otp/with-label.ts
import { Component } from '@angular/core';
import { ArtField, ArtInputOtp, ArtLabel } from '@aranghat/base-angular';

@Component({
  selector: 'sample-input-otp-with-label',
  imports: [ArtField, ArtInputOtp, ArtLabel],
  template: `
    <art-field>
      <art-label slot="label">Verification code</art-label>
      <art-input-otp group-size="3"></art-input-otp>
      <p slot="description">Enter the 6-digit code we sent to your phone.</p>
    </art-field>
  `,
})
export class InputOtpWithLabel {}
