// apps/sandbox/react/src/samples/select/open.tsx
import { Select, SelectItem } from '@aranghat/components-react';

export default function Open() {
  return (
    <>
      <Select value="banana" aria-label="Fruit" open>
        <SelectItem value="apple">Apple</SelectItem>
        <SelectItem value="banana">Banana</SelectItem>
        <SelectItem value="blueberry">Blueberry</SelectItem>
        <SelectItem value="grapes" disabled>Grapes</SelectItem>
        <SelectItem value="pineapple">Pineapple</SelectItem>
      </Select>
    </>
  );
}

// apps/sandbox/angular/src/app/samples/select/open.ts
import { Component } from '@angular/core';
import { ArtSelect, ArtSelectItem } from '@aranghat/components-angular';

@Component({
  selector: 'sample-select-open',
  imports: [ArtSelect, ArtSelectItem],
  template: `
    <art-select value="banana" aria-label="Fruit" open>
      <art-select-item value="apple">Apple</art-select-item>
      <art-select-item value="banana">Banana</art-select-item>
      <art-select-item value="blueberry">Blueberry</art-select-item>
      <art-select-item value="grapes" disabled>Grapes</art-select-item>
      <art-select-item value="pineapple">Pineapple</art-select-item>
    </art-select>
  `,
})
export class SelectOpen {}
