// apps/sandbox/react/src/samples/select/sizes.tsx
import { Select, SelectItem } from '@aranghat/components-react';

export default function Sizes() {
  return (
    <>
      <Select size="sm" placeholder="Small" aria-label="Small">
        <SelectItem value="apple">Apple</SelectItem>
        <SelectItem value="banana">Banana</SelectItem>
        <SelectItem value="blueberry">Blueberry</SelectItem>
        <SelectItem value="grapes" disabled>Grapes</SelectItem>
        <SelectItem value="pineapple">Pineapple</SelectItem>
      </Select>
      <Select placeholder="Medium" aria-label="Medium">
        <SelectItem value="apple">Apple</SelectItem>
        <SelectItem value="banana">Banana</SelectItem>
        <SelectItem value="blueberry">Blueberry</SelectItem>
        <SelectItem value="grapes" disabled>Grapes</SelectItem>
        <SelectItem value="pineapple">Pineapple</SelectItem>
      </Select>
      <Select size="lg" placeholder="Large" aria-label="Large">
        <SelectItem value="apple">Apple</SelectItem>
        <SelectItem value="banana">Banana</SelectItem>
        <SelectItem value="blueberry">Blueberry</SelectItem>
        <SelectItem value="grapes" disabled>Grapes</SelectItem>
        <SelectItem value="pineapple">Pineapple</SelectItem>
      </Select>
    </>
  );
}

// apps/sandbox/angular/src/app/samples/select/sizes.ts
import { Component } from '@angular/core';
import { ArtSelect, ArtSelectItem } from '@aranghat/components-angular';

@Component({
  selector: 'sample-select-sizes',
  imports: [ArtSelect, ArtSelectItem],
  template: `
    <art-select size="sm" placeholder="Small" aria-label="Small">
      <art-select-item value="apple">Apple</art-select-item>
      <art-select-item value="banana">Banana</art-select-item>
      <art-select-item value="blueberry">Blueberry</art-select-item>
      <art-select-item value="grapes" disabled>Grapes</art-select-item>
      <art-select-item value="pineapple">Pineapple</art-select-item>
    </art-select>
    <art-select placeholder="Medium" aria-label="Medium">
      <art-select-item value="apple">Apple</art-select-item>
      <art-select-item value="banana">Banana</art-select-item>
      <art-select-item value="blueberry">Blueberry</art-select-item>
      <art-select-item value="grapes" disabled>Grapes</art-select-item>
      <art-select-item value="pineapple">Pineapple</art-select-item>
    </art-select>
    <art-select size="lg" placeholder="Large" aria-label="Large">
      <art-select-item value="apple">Apple</art-select-item>
      <art-select-item value="banana">Banana</art-select-item>
      <art-select-item value="blueberry">Blueberry</art-select-item>
      <art-select-item value="grapes" disabled>Grapes</art-select-item>
      <art-select-item value="pineapple">Pineapple</art-select-item>
    </art-select>
  `,
})
export class SelectSizes {}
