// apps/sandbox/react/src/samples/input-group/prefix-suffix.tsx
import { Input, InputGroup } from '@aranghat/base-react';

export default function PrefixSuffix() {
  return (
    <>
      <InputGroup>
        <span slot="start">https://</span>
        <Input placeholder="example" aria-label="Domain" />
        <span slot="end">.com</span>
      </InputGroup>
    </>
  );
}

// apps/sandbox/angular/src/app/samples/input-group/prefix-suffix.ts
import { Component } from '@angular/core';
import { ArtInput, ArtInputGroup } from '@aranghat/base-angular';

@Component({
  selector: 'sample-input-group-prefix-suffix',
  imports: [ArtInput, ArtInputGroup],
  template: `
    <art-input-group>
      <span slot="start">https://</span>
      <art-input placeholder="example" aria-label="Domain"></art-input>
      <span slot="end">.com</span>
    </art-input-group>
  `,
})
export class InputGroupPrefixSuffix {}
