// apps/sandbox/angular/src/app/samples/card/login.ts
import { Component } from '@angular/core';
import { ArtButton, ArtCard, ArtField, ArtFieldGroup, ArtInput, ArtLabel } from '@aranghat/base-angular';

@Component({
  selector: 'sample-card-login',
  imports: [ArtButton, ArtCard, ArtField, ArtFieldGroup, ArtInput, ArtLabel],
  template: `
    <art-card>
      <h3 slot="title">Login to your account</h3>
      <p slot="description">Enter your email below to login to your account</p>
      <art-button slot="action" variant="link">Sign up</art-button>
      <art-field-group>
        <art-field>
          <art-label slot="label">Email</art-label>
          <art-input type="email" placeholder="m@example.com"></art-input>
        </art-field>
        <art-field>
          <art-label slot="label">Password</art-label>
          <art-input type="password"></art-input>
        </art-field>
      </art-field-group>
      <art-button slot="footer">Login</art-button>
      <art-button slot="footer" variant="outline">Login with Google</art-button>
    </art-card>
  `,
})
export class CardLogin {}

// apps/sandbox/react/src/samples/card/login.tsx
import { Button, Card, Field, FieldGroup, Input, Label } from '@aranghat/base-react';

export default function Login() {
  return (
    <>
      <Card>
        <h3 slot="title">Login to your account</h3>
        <p slot="description">Enter your email below to login to your account</p>
        <Button slot="action" variant="link">Sign up</Button>
        <FieldGroup>
          <Field>
            <Label slot="label">Email</Label>
            <Input type="email" placeholder="m@example.com" />
          </Field>
          <Field>
            <Label slot="label">Password</Label>
            <Input type="password" />
          </Field>
        </FieldGroup>
        <Button slot="footer">Login</Button>
        <Button slot="footer" variant="outline">Login with Google</Button>
      </Card>
    </>
  );
}
