// apps/sandbox/angular/src/app/samples/carousel/no-controls.ts
import { Component } from '@angular/core';
import { ArtCarousel, ArtCarouselItem } from '@aranghat/components-angular';
import { ArtCard } from '@aranghat/base-angular';

@Component({
  selector: 'sample-carousel-no-controls',
  imports: [ArtCard, ArtCarousel, ArtCarouselItem],
  template: `
    <art-carousel controls="false" drag-free aria-label="Numbers" style="max-width: var(--art-container-sm); --art-carousel-basis: 50%">
      <art-carousel-item>
        <art-card><p class="slide">1</p></art-card>
      </art-carousel-item>
      <art-carousel-item>
        <art-card><p class="slide">2</p></art-card>
      </art-carousel-item>
      <art-carousel-item>
        <art-card><p class="slide">3</p></art-card>
      </art-carousel-item>
      <art-carousel-item>
        <art-card><p class="slide">4</p></art-card>
      </art-carousel-item>
      <art-carousel-item>
        <art-card><p class="slide">5</p></art-card>
      </art-carousel-item>
      <art-carousel-item>
        <art-card><p class="slide">6</p></art-card>
      </art-carousel-item>
    </art-carousel>
  `,
})
export class CarouselNoControls {}

// apps/sandbox/vue/src/samples/carousel/no-controls.vue
<script setup lang="ts">
import { Carousel, CarouselItem } from '@aranghat/components-vue';
import { Card } from '@aranghat/base-vue';
</script>

<template>
  <Carousel controls="false" drag-free aria-label="Numbers" style="max-width: var(--art-container-sm); --art-carousel-basis: 50%">
    <CarouselItem>
      <Card><p class="slide">1</p></Card>
    </CarouselItem>
    <CarouselItem>
      <Card><p class="slide">2</p></Card>
    </CarouselItem>
    <CarouselItem>
      <Card><p class="slide">3</p></Card>
    </CarouselItem>
    <CarouselItem>
      <Card><p class="slide">4</p></Card>
    </CarouselItem>
    <CarouselItem>
      <Card><p class="slide">5</p></Card>
    </CarouselItem>
    <CarouselItem>
      <Card><p class="slide">6</p></Card>
    </CarouselItem>
  </Carousel>
</template>
