// apps/sandbox/react/src/samples/carousel/no-controls.tsx
import { Carousel, CarouselItem } from '@aranghat/components-react';
import { Card } from '@aranghat/base-react';

export default function NoControls() {
  return (
    <>
      <Carousel controls="false" drag-free aria-label="Numbers" style={{ maxWidth: 'var(--art-container-sm)', '--art-carousel-basis': '50%' }}>
        <CarouselItem>
          <Card><p className="slide">1</p></Card>
        </CarouselItem>
        <CarouselItem>
          <Card><p className="slide">2</p></Card>
        </CarouselItem>
        <CarouselItem>
          <Card><p className="slide">3</p></Card>
        </CarouselItem>
        <CarouselItem>
          <Card><p className="slide">4</p></Card>
        </CarouselItem>
        <CarouselItem>
          <Card><p className="slide">5</p></Card>
        </CarouselItem>
        <CarouselItem>
          <Card><p className="slide">6</p></Card>
        </CarouselItem>
      </Carousel>
    </>
  );
}

// apps/sandbox/vue/src/samples/carousel/no-controls.vue
<script setup lang="ts">
import { Carousel, CarouselItem } from '@aranghat/components-vue';
import { Card } from '@aranghat/base-vue';
</script>

<template>
  <Carousel controls="false" drag-free aria-label="Numbers" style="max-width: var(--art-container-sm); --art-carousel-basis: 50%">
    <CarouselItem>
      <Card><p class="slide">1</p></Card>
    </CarouselItem>
    <CarouselItem>
      <Card><p class="slide">2</p></Card>
    </CarouselItem>
    <CarouselItem>
      <Card><p class="slide">3</p></Card>
    </CarouselItem>
    <CarouselItem>
      <Card><p class="slide">4</p></Card>
    </CarouselItem>
    <CarouselItem>
      <Card><p class="slide">5</p></Card>
    </CarouselItem>
    <CarouselItem>
      <Card><p class="slide">6</p></Card>
    </CarouselItem>
  </Carousel>
</template>
