// apps/sandbox/angular/src/app/samples/kbd/in-button.ts
import { Component } from '@angular/core';
import { ArtButton, ArtKbd } from '@aranghat/base-angular';

@Component({
  selector: 'sample-kbd-in-button',
  imports: [ArtButton, ArtKbd],
  template: `
    <art-button variant="outline" size="sm">
      Accept
      <art-kbd slot="end">⏎</art-kbd>
    </art-button>
    <art-button variant="outline" size="sm">
      Cancel
      <art-kbd slot="end">Esc</art-kbd>
    </art-button>
  `,
})
export class KbdInButton {}

// apps/sandbox/react/src/samples/kbd/in-button.tsx
import { Button, Kbd } from '@aranghat/base-react';

export default function InButton() {
  return (
    <>
      <Button variant="outline" size="sm">
        Accept
        <Kbd slot="end">⏎</Kbd>
      </Button>
      <Button variant="outline" size="sm">
        Cancel
        <Kbd slot="end">Esc</Kbd>
      </Button>
    </>
  );
}
