// apps/sandbox/react/src/samples/tabs/vertical.tsx
import { Tab, TabPanel, Tabs } from '@aranghat/components-react';

export default function Vertical() {
  return (
    <>
      <Tabs value="general" orientation="vertical">
        <Tab value="general">General</Tab>
        <Tab value="security">Security</Tab>
        <Tab value="billing">Billing</Tab>
        <TabPanel value="general"><p>General settings.</p></TabPanel>
        <TabPanel value="security"><p>Security settings.</p></TabPanel>
        <TabPanel value="billing"><p>Billing settings.</p></TabPanel>
      </Tabs>
    </>
  );
}

// apps/sandbox/angular/src/app/samples/tabs/vertical.ts
import { Component } from '@angular/core';
import { ArtTab, ArtTabPanel, ArtTabs } from '@aranghat/components-angular';

@Component({
  selector: 'sample-tabs-vertical',
  imports: [ArtTab, ArtTabPanel, ArtTabs],
  template: `
    <art-tabs value="general" orientation="vertical">
      <art-tab value="general">General</art-tab>
      <art-tab value="security">Security</art-tab>
      <art-tab value="billing">Billing</art-tab>
      <art-tab-panel value="general"><p>General settings.</p></art-tab-panel>
      <art-tab-panel value="security"><p>Security settings.</p></art-tab-panel>
      <art-tab-panel value="billing"><p>Billing settings.</p></art-tab-panel>
    </art-tabs>
  `,
})
export class TabsVertical {}
