// apps/sandbox/angular/src/app/samples/input/file.ts
import { Component } from '@angular/core';
import { ArtInput, ArtLabel } from '@aranghat/base-angular';

@Component({
  selector: 'sample-input-file',
  imports: [ArtInput, ArtLabel],
  template: `
    <div style="display:flex;flex-direction:column;gap:var(--art-space-2);width:20rem;max-width:100%"><art-label for="picture">Picture</art-label><art-input id="picture" type="file"></art-input></div>
  `,
})
export class InputFile {}

// apps/sandbox/react/src/samples/input/file.tsx
import { Input, Label } from '@aranghat/base-react';

export default function File() {
  return (
    <>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--art-space-2)', width: '20rem', maxWidth: '100%' }}><Label htmlFor="picture">Picture</Label><Input id="picture" type="file"></Input></div>
    </>
  );
}
