// apps/sandbox/angular/src/app/samples/data-table-page/empty.ts
import { Component } from '@angular/core';
import { ArtDataTablePage } from '@aranghat/widgets-angular';
import { ArtButton, ArtCheckbox, ArtTable } from '@aranghat/base-angular';

@Component({
  selector: 'sample-data-table-page-empty',
  imports: [ArtButton, ArtCheckbox, ArtDataTablePage, ArtTable],
  template: `
    <art-data-table-page filter-placeholder="Filter tasks…" total="0" page-count="1" page-size="10" filter="zzz">
      <art-button slot="actions" variant="outline" size="sm">Export</art-button>
      <art-button slot="filters" variant="outline" size="sm">Status</art-button>
      <art-button slot="filters" variant="outline" size="sm">Priority</art-button>
      <art-button slot="view" variant="outline" size="sm">View</art-button>
      <art-table>
        <table>
          <thead>
            <tr>
              <th><art-checkbox aria-label="Select all"></art-checkbox><span class="sr-only">Select</span></th>
              <th>Task</th>
              <th>Title</th>
              <th>Status</th>
              <th>Priority</th>
            </tr>
          </thead>
          <tbody>
            <tr><td colspan="5" style="text-align: center; padding-block: var(--art-space-6)">No results.</td></tr>
          </tbody>
        </table>
      </art-table>
    </art-data-table-page>
  `,
})
export class DataTablePageEmpty {}

// apps/sandbox/vue/src/samples/data-table-page/empty.vue
<script setup lang="ts">
import { DataTablePage } from '@aranghat/widgets-vue';
import { Button, Checkbox, Table } from '@aranghat/base-vue';
</script>

<template>
  <DataTablePage filter-placeholder="Filter tasks…" total="0" page-count="1" page-size="10" filter="zzz">
    <Button slot="actions" variant="outline" size="sm">Export</Button>
    <Button slot="filters" variant="outline" size="sm">Status</Button>
    <Button slot="filters" variant="outline" size="sm">Priority</Button>
    <Button slot="view" variant="outline" size="sm">View</Button>
    <Table>
      <table>
        <thead>
          <tr>
            <th><Checkbox aria-label="Select all" /><span class="sr-only">Select</span></th>
            <th>Task</th>
            <th>Title</th>
            <th>Status</th>
            <th>Priority</th>
          </tr>
        </thead>
        <tbody>
          <tr><td colspan="5" style="text-align: center; padding-block: var(--art-space-6)">No results.</td></tr>
        </tbody>
      </table>
    </Table>
  </DataTablePage>
</template>
