// apps/sandbox/react/src/samples/item/variants.tsx
import { Item } from '@aranghat/base-react';

export default function Variants() {
  return (
    <>
      <Item>
        <p slot="title">Default</p>
        <p slot="description">No border, no fill.</p>
      </Item>
      <Item variant="outline">
        <p slot="title">Outline</p>
        <p slot="description">Bordered.</p>
      </Item>
      <Item variant="muted">
        <p slot="title">Muted</p>
        <p slot="description">Filled with the muted background.</p>
      </Item>
    </>
  );
}

// apps/sandbox/angular/src/app/samples/item/variants.ts
import { Component } from '@angular/core';
import { ArtItem } from '@aranghat/base-angular';

@Component({
  selector: 'sample-item-variants',
  imports: [ArtItem],
  template: `
    <art-item>
      <p slot="title">Default</p>
      <p slot="description">No border, no fill.</p>
    </art-item>
    <art-item variant="outline">
      <p slot="title">Outline</p>
      <p slot="description">Bordered.</p>
    </art-item>
    <art-item variant="muted">
      <p slot="title">Muted</p>
      <p slot="description">Filled with the muted background.</p>
    </art-item>
  `,
})
export class ItemVariants {}
