// apps/sandbox/react/src/samples/navigation-menu/active.tsx
import { NavigationMenu, NavigationMenuItem } from '@aranghat/navigation-react';

export default function Active() {
  return (
    <>
      <NavigationMenu>
        <NavigationMenuItem label="Home" href="#" active />
        <NavigationMenuItem label="Pricing" href="#pricing" />
        <NavigationMenuItem label="Blog" href="#blog" />
      </NavigationMenu>
    </>
  );
}

// apps/sandbox/angular/src/app/samples/navigation-menu/active.ts
import { Component } from '@angular/core';
import { ArtNavigationMenu, ArtNavigationMenuItem } from '@aranghat/navigation-angular';

@Component({
  selector: 'sample-navigation-menu-active',
  imports: [ArtNavigationMenu, ArtNavigationMenuItem],
  template: `
    <art-navigation-menu>
      <art-navigation-menu-item label="Home" href="#" active></art-navigation-menu-item>
      <art-navigation-menu-item label="Pricing" href="#pricing"></art-navigation-menu-item>
      <art-navigation-menu-item label="Blog" href="#blog"></art-navigation-menu-item>
    </art-navigation-menu>
  `,
})
export class NavigationMenuActive {}
