// apps/sandbox/angular/src/app/samples/dropdown-menu/checkboxes.ts
import { Component } from '@angular/core';
import { ArtDropdownMenu, ArtDropdownMenuItem, ArtDropdownMenuLabel, ArtDropdownMenuSeparator } from '@aranghat/navigation-angular';
import { ArtButton } from '@aranghat/base-angular';

@Component({
  selector: 'sample-dropdown-menu-checkboxes',
  imports: [ArtButton, ArtDropdownMenu, ArtDropdownMenuItem, ArtDropdownMenuLabel, ArtDropdownMenuSeparator],
  template: `
    <art-dropdown-menu open>
      <art-button slot="trigger" variant="outline">View</art-button>
      <art-dropdown-menu-label>Appearance</art-dropdown-menu-label>
      <art-dropdown-menu-separator></art-dropdown-menu-separator>
      <art-dropdown-menu-item type="checkbox" value="status" checked>Status bar</art-dropdown-menu-item>
      <art-dropdown-menu-item type="checkbox" value="activity" disabled>Activity bar</art-dropdown-menu-item>
      <art-dropdown-menu-item type="checkbox" value="panel">Panel</art-dropdown-menu-item>
    </art-dropdown-menu>
  `,
})
export class DropdownMenuCheckboxes {}

// apps/sandbox/react/src/samples/dropdown-menu/checkboxes.tsx
import { DropdownMenu, MenuItem, MenuLabel, MenuSeparator } from '@aranghat/navigation-react';
import { Button } from '@aranghat/base-react';

export default function Checkboxes() {
  return (
    <>
      <DropdownMenu open>
        <Button slot="trigger" variant="outline">View</Button>
        <MenuLabel>Appearance</MenuLabel>
        <MenuSeparator />
        <MenuItem type="checkbox" value="status" checked>Status bar</MenuItem>
        <MenuItem type="checkbox" value="activity" disabled>Activity bar</MenuItem>
        <MenuItem type="checkbox" value="panel">Panel</MenuItem>
      </DropdownMenu>
    </>
  );
}
