// apps/sandbox/angular/src/app/samples/dropdown-menu/links.ts
import { Component } from '@angular/core';
import { ArtDropdownMenu, ArtMenuItem } from '@aranghat/navigation-angular';
import { ArtButton } from '@aranghat/base-angular';

@Component({
  selector: 'sample-dropdown-menu-links',
  imports: [ArtButton, ArtDropdownMenu, ArtMenuItem],
  template: `
    <art-dropdown-menu>
      <art-button slot="trigger" variant="outline">Go to</art-button>
      <art-menu-item href="#dashboard">Dashboard</art-menu-item>
      <art-menu-item href="#reports">Reports</art-menu-item>
      <art-menu-item href="https://example.com" target="_blank">Docs ↗</art-menu-item>
    </art-dropdown-menu>
  `,
})
export class DropdownMenuLinks {}

// apps/sandbox/react/src/samples/dropdown-menu/links.tsx
import { DropdownMenu, MenuItem } from '@aranghat/navigation-react';
import { Button } from '@aranghat/base-react';

export default function Links() {
  return (
    <>
      <DropdownMenu>
        <Button slot="trigger" variant="outline">Go to</Button>
        <MenuItem href="#dashboard">Dashboard</MenuItem>
        <MenuItem href="#reports">Reports</MenuItem>
        <MenuItem href="https://example.com" target="_blank">Docs ↗</MenuItem>
      </DropdownMenu>
    </>
  );
}
