// apps/sandbox/angular/src/app/samples/native-select/with-label.ts
import { Component } from '@angular/core';
import { ArtLabel, ArtNativeSelect } from '@aranghat/base-angular';

@Component({
  selector: 'sample-native-select-with-label',
  imports: [ArtLabel, ArtNativeSelect],
  template: `
    <art-label for="status">Status</art-label>
    <art-native-select id="status" value="in-progress">
      <option value="">Select status</option>
      <option value="todo">Todo</option>
      <option value="in-progress">In Progress</option>
      <option value="done">Done</option>
      <option value="cancelled">Cancelled</option>
    </art-native-select>
  `,
})
export class NativeSelectWithLabel {}

// apps/sandbox/vue/src/samples/native-select/with-label.vue
<script setup lang="ts">
import { Label, NativeSelect } from '@aranghat/base-vue';
</script>

<template>
  <Label for="status">Status</Label>
  <NativeSelect id="status" value="in-progress">
    <option value="">Select status</option>
    <option value="todo">Todo</option>
    <option value="in-progress">In Progress</option>
    <option value="done">Done</option>
    <option value="cancelled">Cancelled</option>
  </NativeSelect>
</template>
