// apps/sandbox/angular/src/app/samples/bubble/group.ts
import { Component } from '@angular/core';
import { ArtBubble, ArtBubbleGroup } from '@aranghat/components-angular';

@Component({
  selector: 'sample-bubble-group',
  imports: [ArtBubble, ArtBubbleGroup],
  template: `
    <art-bubble-group>
      <art-bubble variant="muted">First of three.</art-bubble>
      <art-bubble variant="muted">Second, from the same sender.</art-bubble>
      <art-bubble variant="muted">Third.</art-bubble>
    </art-bubble-group>
  `,
})
export class BubbleGroup {}

// apps/sandbox/react/src/samples/bubble/group.tsx
import { Bubble, BubbleGroup } from '@aranghat/components-react';

export default function Group() {
  return (
    <>
      <BubbleGroup>
        <Bubble variant="muted">First of three.</Bubble>
        <Bubble variant="muted">Second, from the same sender.</Bubble>
        <Bubble variant="muted">Third.</Bubble>
      </BubbleGroup>
    </>
  );
}
