// apps/sandbox/angular/src/app/samples/textarea/invalid.ts
import { Component } from '@angular/core';
import { ArtLabel, ArtTextarea } from '@aranghat/base-angular';

@Component({
  selector: 'sample-textarea-invalid',
  imports: [ArtLabel, ArtTextarea],
  template: `
    <art-label for="bio">Bio</art-label>
    <art-textarea id="bio" value="Too short" invalid aria-describedby="bio-error"></art-textarea>
    <p id="bio-error">Bio must be at least 10 characters.</p>
  `,
})
export class TextareaInvalid {}

// apps/sandbox/react/src/samples/textarea/invalid.tsx
import { Label, Textarea } from '@aranghat/base-react';

export default function Invalid() {
  return (
    <>
      <Label htmlFor="bio">Bio</Label>
      <Textarea id="bio" value="Too short" invalid aria-describedby="bio-error" />
      <p id="bio-error">Bio must be at least 10 characters.</p>
    </>
  );
}
