// apps/sandbox/react/src/samples/button/rounded.tsx
import { Button, Icon } from '@aranghat/base-react';
import { plus } from '@aranghat/icons/plus';

export default function Rounded() {
  return (
    <>
      <Button rounded>Button</Button>
      <Button rounded variant="outline">Outline</Button>
      <Button rounded icon aria-label="Add">
        <Icon icon={plus} />
      </Button>
    </>
  );
}

// apps/sandbox/angular/src/app/samples/button/rounded.ts
import { Component } from '@angular/core';
import { ArtButton, ArtIcon } from '@aranghat/base-angular';
import { plus } from '@aranghat/icons/plus';

@Component({
  selector: 'sample-button-rounded',
  imports: [ArtButton, ArtIcon],
  template: `
    <art-button rounded>Button</art-button>
    <art-button rounded variant="outline">Outline</art-button>
    <art-button rounded icon aria-label="Add">
      <art-icon [icon]="plus"></art-icon>
    </art-button>
  `,
})
export class ButtonRounded {
  plus = plus;
}
