// apps/sandbox/react/src/samples/button-group/sizes.tsx
import { Button, ButtonGroup } from '@aranghat/base-react';

export default function Sizes() {
  return (
    <>
      <ButtonGroup>
        <Button variant="outline" size="sm">Small</Button>
        <Button variant="outline" size="sm">Small</Button>
      </ButtonGroup>
      <ButtonGroup>
        <Button variant="outline" size="lg">Large</Button>
        <Button variant="outline" size="lg">Large</Button>
      </ButtonGroup>
    </>
  );
}

// apps/sandbox/angular/src/app/samples/button/sizes.ts
import { Component } from '@angular/core';
import { ArtButton } from '@aranghat/base-angular';

@Component({
  selector: 'sample-button-sizes',
  imports: [ArtButton],
  template: `
    <art-button size="sm">Small</art-button>
    <art-button>Medium</art-button>
    <art-button size="lg">Large</art-button>
  `,
})
export class ButtonSizes {}
