// apps/sandbox/angular/src/app/samples/toaster/variants.ts
import { Component } from '@angular/core';
import { ArtToast, ArtToaster } from '@aranghat/components-angular';

@Component({
  selector: 'sample-toaster-variants',
  imports: [ArtToast, ArtToaster],
  template: `
    <art-toaster inline>
      <art-toast duration="0">Default</art-toast>
      <art-toast variant="success" duration="0">Success</art-toast>
      <art-toast variant="error" duration="0">Error</art-toast>
      <art-toast variant="warning" duration="0">Warning</art-toast>
      <art-toast variant="info" duration="0">Info</art-toast>
      <art-toast variant="loading" duration="0">Loading…</art-toast>
    </art-toaster>
  `,
})
export class ToasterVariants {}

// apps/sandbox/react/src/samples/toaster/variants.tsx
import { Toast, Toaster } from '@aranghat/components-react';

export default function Variants() {
  return (
    <>
      <Toaster inline>
        <Toast duration="0">Default</Toast>
        <Toast variant="success" duration="0">Success</Toast>
        <Toast variant="error" duration="0">Error</Toast>
        <Toast variant="warning" duration="0">Warning</Toast>
        <Toast variant="info" duration="0">Info</Toast>
        <Toast variant="loading" duration="0">Loading…</Toast>
      </Toaster>
    </>
  );
}
