// apps/sandbox/react/src/samples/common-dialogs/alert.tsx
import { useState } from 'react';
import { Button } from '@aranghat/base-react';
import { alert } from '@aranghat/modals';

export default function Alert() {
  const [result, setResult] = useState('');
  // alert() mounts the dialog itself and resolves when it closes — no element to render
  const ask = async () => {
    await alert({ title: 'Export finished', description: 'Your report is ready to download.' });
    setResult('Acknowledged.');
  };
  return (
    <>
      <Button variant="outline" onClick={ask}>Show alert</Button>
      <p>{result}</p>
    </>
  );
}

// apps/sandbox/angular/src/app/samples/common-dialogs/alert.ts
import { Component } from '@angular/core';
import { ArtButton } from '@aranghat/base-angular';
import { alert } from '@aranghat/modals';

@Component({
  selector: 'sample-common-dialogs-alert',
  imports: [ArtButton],
  template: `
    <art-button variant="outline" (click)="ask()">Show alert</art-button>
    <p>{{ result }}</p>
  `,
})
export class CommonDialogsAlert {
  result = '';
  // alert() mounts the dialog itself and resolves when it closes — no element to render
  async ask() {
    await alert({ title: 'Export finished', description: 'Your report is ready to download.' });
    this.result = 'Acknowledged.';
  }
}
