// apps/sandbox/angular/src/app/samples/combobox/groups.ts
import { Component } from '@angular/core';
import { ArtCombobox, ArtComboboxGroup, ArtComboboxItem } from '@aranghat/components-angular';

@Component({
  selector: 'sample-combobox-groups',
  imports: [ArtCombobox, ArtComboboxGroup, ArtComboboxItem],
  template: `
    <art-combobox placeholder="Pick a fruit or a vegetable" aria-label="Produce">
      <art-combobox-group label="Fruits">
        <art-combobox-item value="apple">Apple</art-combobox-item>
        <art-combobox-item value="banana">Banana</art-combobox-item>
      </art-combobox-group>
      <art-combobox-group label="Vegetables">
        <art-combobox-item value="carrot">Carrot</art-combobox-item>
        <art-combobox-item value="pea">Pea</art-combobox-item>
      </art-combobox-group>
    </art-combobox>
  `,
})
export class ComboboxGroups {}

// apps/sandbox/react/src/samples/combobox/groups.tsx
import { Combobox, ComboboxGroup, ComboboxItem } from '@aranghat/components-react';

export default function Groups() {
  return (
    <>
      <Combobox placeholder="Pick a fruit or a vegetable" aria-label="Produce">
        <ComboboxGroup label="Fruits">
          <ComboboxItem value="apple">Apple</ComboboxItem>
          <ComboboxItem value="banana">Banana</ComboboxItem>
        </ComboboxGroup>
        <ComboboxGroup label="Vegetables">
          <ComboboxItem value="carrot">Carrot</ComboboxItem>
          <ComboboxItem value="pea">Pea</ComboboxItem>
        </ComboboxGroup>
      </Combobox>
    </>
  );
}
