// apps/sandbox/angular/src/app/samples/combobox/multiple.ts
import { Component } from '@angular/core';
import { ArtCombobox, ArtComboboxItem } from '@aranghat/components-angular';

@Component({
  selector: 'sample-combobox-multiple',
  imports: [ArtCombobox, ArtComboboxItem],
  template: `
    <art-combobox multiple placeholder="Add frameworks…" aria-label="Frameworks" show-clear>
      <art-combobox-item value="next">Next.js</art-combobox-item>
      <art-combobox-item value="sveltekit">SvelteKit</art-combobox-item>
      <art-combobox-item value="nuxt">Nuxt.js</art-combobox-item>
      <art-combobox-item value="remix" disabled>Remix</art-combobox-item>
      <art-combobox-item value="astro">Astro</art-combobox-item>
    </art-combobox>
  `,
})
export class ComboboxMultiple {}

// apps/sandbox/react/src/samples/combobox/multiple.tsx
import { Combobox, ComboboxItem } from '@aranghat/components-react';

export default function Multiple() {
  return (
    <>
      <Combobox multiple placeholder="Add frameworks…" aria-label="Frameworks" show-clear>
        <ComboboxItem value="next">Next.js</ComboboxItem>
        <ComboboxItem value="sveltekit">SvelteKit</ComboboxItem>
        <ComboboxItem value="nuxt">Nuxt.js</ComboboxItem>
        <ComboboxItem value="remix" disabled>Remix</ComboboxItem>
        <ComboboxItem value="astro">Astro</ComboboxItem>
      </Combobox>
    </>
  );
}
